# Generated by Django 4.2.7 on 2024-03-25 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("traininglog", "0004_stravaapi_stravalogin"),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="stravaLogin",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="traininglog.stravalogin",
            ),
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                ("workoutId", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignedWorkouts",
                        to="traininglog.athlete",
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="createdWorkouts",
                        to="traininglog.coach",
                    ),
                ),
            ],
        ),
    ]
