# Generated by Django 4.2.7 on 2024-04-11 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("traininglog", "0005_athlete_stravalogin_workout"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="assignedDate",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="workout",
            name="title",
            field=models.CharField(default="Workout", max_length=30),
        ),
    ]
