# Generated by Django 4.2.7 on 2024-04-14 21:48

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("traininglog", "0007_remove_workout_athlete_workout_athletes_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TrainingGroups",
            new_name="TrainingGroup",
        ),
        migrations.AddField(
            model_name="bike",
            name="tpye",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="other",
            name="tpye",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="run",
            name="tpye",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="swim",
            name="tpye",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bike",
            name="startDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 14, 21, 46, 57, 395300, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="other",
            name="startDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 14, 21, 46, 57, 395300, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="startDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 14, 21, 46, 57, 395300, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="swim",
            name="startDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 14, 21, 46, 57, 395300, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
