# Generated by Django 4.2.7 on 2024-04-14 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traininglog", "0008_rename_traininggroups_traininggroup_bike_tpye_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bike",
            name="tpye",
        ),
        migrations.RemoveField(
            model_name="other",
            name="tpye",
        ),
        migrations.RemoveField(
            model_name="run",
            name="tpye",
        ),
        migrations.RemoveField(
            model_name="swim",
            name="tpye",
        ),
        migrations.AddField(
            model_name="bike",
            name="activityType",
            field=models.CharField(default="bike", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bike",
            name="description",
            field=models.TextField(default="A bike ride"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="other",
            name="description",
            field=models.TextField(default="An activity"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="run",
            name="activityType",
            field=models.CharField(default="run", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="run",
            name="description",
            field=models.TextField(default="A run"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="swim",
            name="activityType",
            field=models.CharField(default="swim", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="swim",
            name="description",
            field=models.TextField(default="A swim"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bike",
            name="startDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 14, 23, 43, 27, 852822, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="other",
            name="activityType",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="other",
            name="startDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 14, 23, 43, 27, 852822, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="startDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 14, 23, 43, 27, 852822, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="swim",
            name="startDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 14, 23, 43, 27, 852822, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
