# Generated by Django 4.2.7 on 2024-04-15 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "traininglog",
            "0009_remove_bike_tpye_remove_other_tpye_remove_run_tpye_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bike",
            name="startDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 15, 2, 8, 20, 188043, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="other",
            name="startDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 15, 2, 8, 20, 188043, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="startDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 15, 2, 8, 20, 188043, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="swim",
            name="startDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 15, 2, 8, 20, 188043, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
