# Generated by Django 4.2.7 on 2024-04-22 01:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("traininglog", "0016_alter_bike_startdate_alter_other_startdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bike",
            name="startDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 22, 1, 25, 55, 290216, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="other",
            name="startDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 22, 1, 25, 55, 290216, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="startDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 22, 1, 25, 55, 290216, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="swim",
            name="startDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 22, 1, 25, 55, 290216, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("commentId", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                ("postDate", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "bikeActivity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="traininglog.bike",
                    ),
                ),
                (
                    "otherActivity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="traininglog.other",
                    ),
                ),
                (
                    "runActivity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="traininglog.run",
                    ),
                ),
                (
                    "swimActivity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="traininglog.swim",
                    ),
                ),
            ],
        ),
    ]
