# Generated by Django 4.2.7 on 2024-05-07 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traininglog", "0017_alter_bike_startdate_alter_other_startdate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stravalogin",
            name="stravaAuthorizationScope",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bike",
            name="startDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 7, 17, 1, 4, 387513, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="other",
            name="startDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 7, 17, 1, 4, 387513, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="startDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 7, 17, 1, 4, 387513, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="swim",
            name="startDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 7, 17, 1, 4, 387513, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
